### ISSUE TITLE
Unable to install Errand on CentOS 5.4

### ISSUE THREAD

**Issue by michele** [auxesis/visage#7] opened 2010-01-24 18:01 UTC
When I run `gem bundle` it gets stuck compiling native extensions for Errand. This is what I get:

```
ERROR:  Error installing errand:
    ERROR: Failed to build gem native extension.

/opt/ruby-enterprise-1.8.7-2010.01/bin/ruby extconf.rb
checking for main() in -lz... yes
checking for main() in -lpng... yes
checking for main() in -lfreetype... yes
checking for main() in -lart_lgpl_2... no
checking for rrd_first() in -lrrd... yes
creating Makefile

make
Makefile:137: warning: overriding commands for target `/opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/errand-0.7.0/lib'
Makefile:135: warning: ignoring old commands for target `/opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/errand-0.7.0/lib'
gcc -I. -I. -I/opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/1.8/x86_64-linux -I.  -fPIC -g -O2   -DHAVE_RRD_DUMP_R_2  -c rrdtool_main.c
In file included from rrdtool_main.c:9:
rrd_info.h:35: error: expected specifier-qualifier-list before ‘rrd_info_type_t’
rrdtool_main.c: In function ‘rb_rrd_info’:
rrdtool_main.c:178: warning: assignment makes pointer from integer without a cast
rrdtool_main.c:186: error: ‘info_t’ has no member named ‘type’
rrdtool_main.c:187: error: ‘RD_I_VAL’ undeclared (first use in this function)
rrdtool_main.c:187: error: (Each undeclared identifier is reported only once
rrdtool_main.c:187: error: for each function it appears in.)
rrdtool_main.c:188: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:188: error: non-floating-point argument to function ‘isnan’
rrdtool_main.c:192: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:195: error: ‘RD_I_CNT’ undeclared (first use in this function)
rrdtool_main.c:196: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:198: error: ‘RD_I_STR’ undeclared (first use in this function)
rrdtool_main.c:199: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:200: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:204: error: ‘info_t’ has no member named ‘next’
make: *** [rrdtool_main.o] Error 1


Gem files will remain installed in /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/errand-0.7.0 for inspection.
Results logged to /opt/ruby-enterprise-1.8.7-2010.01/lib/ruby/gems/1.8/gems/errand-0.7.0/gem_make.out
```

**Comment by auxesis** [comment] 2010-01-24 21:58
Hmm, ok. I haven't tested with REE before, so I'll try and reproduce. 

I take it you have the necessary RRDtool headers installed?

**Comment by michele** [comment] 2010-01-24 22:04
I've got the following installed via yum:

```
rrdtool.i386                              1.2.27-3.el5                 installed
rrdtool.x86_64                            1.2.27-3.el5                 installed
rrdtool-devel.i386                        1.2.27-3.el5                 installed
rrdtool-devel.x86_64                      1.2.27-3.el5                 installed
rrdtool-ruby.x86_64                       1.2.27-3.el5                 installed
ruby-RRDtool.x86_64                       0.6.0-6.el5                  installed
```

**Comment by auxesis** [comment] 2010-01-24 22:08
thanks for the info

**Comment by LordCope** [comment] 2010-02-08 07:14
Hi Lindsay,

I have similar problems buiding native extensions for errand on Ubuntu Hardy:
stephen@ubuntu-test:~/visage$ bundle install
Installing errand (0.7.0) from .gem files at /home/stephen/visage/vendor/cache with native extensions /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:504:in `build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

/usr/bin/ruby1.8 extconf.rb
checking for main() in -lz... yes
checking for main() in -lpng... yes
checking for main() in -lfreetype... yes
checking for main() in -lart_lgpl_2... yes
checking for rrd_first() in -lrrd... yes
creating Makefile

make
Makefile:129: warning: overriding commands for target `/home/stephen/visage/vendor/gems/gems/errand-0.7.0/lib'
Makefile:127: warning: ignoring old commands for target`/home/stephen/visage/vendor/gems/gems/errand-0.7.0/lib'
cc -I. -I. -I/usr/lib/ruby/1.8/i486-linux -I.  -fPIC -fno-strict-aliasing -g -g -O2  -fPIC -DHAVE_RRD_DUMP_R_2  -c rrdtool_main.c
In file included from rrdtool_main.c:9:
rrd_info.h:35: error: expected specifier-qualifier-list before ‘rrd_info_type_t’
rrdtool_main.c: In function ‘rb_rrd_info’:
rrdtool_main.c:178: warning: assignment makes pointer from integer without a cast
rrdtool_main.c:186: error: ‘info_t’ has no member named ‘type’
rrdtool_main.c:187: error: ‘RD_I_VAL’ undeclared (first use in this function)
rrdtool_main.c:187: error: (Each undeclared identifier is reported only once
rrdtool_main.c:187: error: for each function it appears in.)
rrdtool_main.c:188: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:188: error: non-floating-point argument to function ‘isnan’
rrdtool_main.c:192: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:195: error: ‘RD_I_CNT’ undeclared (first use in this function)
rrdtool_main.c:196: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:198: error: ‘RD_I_STR’ undeclared (first use in this function)
rrdtool_main.c:199: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:200: error: ‘info_t’ has no member named ‘value’
rrdtool_main.c:204: error: ‘info_t’ has no member named ‘next’
make: **\* [rrdtool_main.o] Error 1

Gem files will remain installed in /home/stephen/visage/vendor/gems/gems/errand-0.7.0 for inspection.
Results logged to /home/stephen/visage/vendor/gems/gems/errand-0.7.0/gem_make.out
    from /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:467:in `each'
    from /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:467:in`build_extensions'
    from /usr/local/lib/site_ruby/1.8/rubygems/installer.rb:219:in `install'
    from /var/lib/gems/1.8/gems/bundler-0.9.3/lib/bundler/source.rb:127:in`install'
    from /var/lib/gems/1.8/gems/bundler-0.9.3/lib/bundler/installer.rb:25:in `run'
    from /var/lib/gems/1.8/gems/bundler-0.9.3/lib/bundler/installer.rb:15:in`each'
    from /var/lib/gems/1.8/gems/bundler-0.9.3/lib/bundler/installer.rb:15:in `run'
    from /var/lib/gems/1.8/gems/bundler-0.9.3/lib/bundler/installer.rb:6:in`install'
     ... 8 levels...
    from /var/lib/gems/1.8/gems/bundler-0.9.3/lib/bundler/vendor/thor.rb:124:in `start'
    from /var/lib/gems/1.8/gems/bundler-0.9.3/bin/bundle:4
    from /usr/local/bin/bundle:19:in`load'
    from /usr/local/bin/bundle:19

S.

**Comment by auxesis** [comment] 2010-02-09 08:49
Hmm ok. Looks like i'll have to expand the scope of my debugging to some clean room VMs.

**Comment by damm** [comment] 2010-02-19 00:03
Hi, it's actually a problem with the gem itself; it needs to be patched see,

http://rubyforge.org/tracker/index.php?func=detail&aid=26207&group_id=826&atid=3261

**Comment by auxesis** [comment] 2010-02-19 03:33
Actually Visage should be using Errand, which is based off the original Ruby RRDtool bindings. I've seen that patch before but it doesn't apply to the C library component of Errand. 

Good news is that I can reproduce the REE + CentOS bugs - now I just need to fix them. :-)

**Comment by auxesis** [comment] 2010-02-19 14:59
Steps to reproduce: 
- install REE from [source or deb](http://www.rubyenterpriseedition.com/download.html)
- checkout Errand (git clone git://github.com/auxesis/rubyrrdtool.git)
- within Errand checkout, run: 

`ruby extconf.rb`  
`make`

This only seems to happen on 64-bit platforms.

**Comment by auxesis** [comment] 2010-02-19 18:17
I poked some more and it's not actually a 64-bit issue, it's a rrdtool 1.2/1.3 issue. 

Errand compiles against 1.3 successfully, but not against 1.2. 

The quick fix for this is to make sure you're using rrdtool 1.3 (with the appropriate dev packages). 

I'm seriously considering rewriting the Errand rrdtool bindings using [ruby-ffi](http://github.com/ffi/ffi), which will simplify the installation of Visage tremendously. Basically ruby-ffi will inspect the available rrdtool libraries on the system and generate bindings appropriately. 

This means that when you install Visage, you won't need to install any development headers for rrdtool, and you're going to have rrdtool installed anyhow for collectd, so Visage/Errand will be pure Ruby.

**Comment by auxesis** [comment] 2010-05-19 08:06
So the temporary fix that I pushed and _completely_ neglected to mention here (I am an immense slacker) is that Errand no longer has a C extension to compile - it simply wraps the system's packaged RRDtool Ruby binding. 

So now to get this working, just install either the `librrd-ruby` package on Debian/Ubuntu, or `rrdtool-ruby` on RHEL/CentOS,

**Closed as completed by auxesis** 2010-05-19 08:06 UTC
