### ISSUE TITLE
Strange values returned by ajax request

### ISSUE THREAD

**Issue by kwellman** [auxesis/visage#16] opened 2010-05-17 19:34 UTC
The data array returned by the ajax request often contains a strange value for its last item. It's either very small or very large. 

ex:
curl http://localhost:4567/data/localhost/cpu-1?callback=Request.JSONP.request_map.request_1

returns a value of 6.91304830802425e-310 for the last element in the localhost/cpu-interrupt/value/data

I've seen this value become huge sometimes (seems to randomly fluctuate).

**Comment by kwellman** [comment] 2010-05-17 19:39
After testing this by modifying the javascript to simply ignore the last data item, another bug was revealed. When the data is all zeros, the graph is not rendered properly (the horizontal axis labels are not formatted correctly). It seems to cause an exception in the javascript.

**Comment by auxesis** [comment] 2010-05-20 01:48
Ok, the first bug you reported is a dupe of #13. 

I'll have a look at the second once I get the first sorted.

**Comment by auxesis** [comment] 2010-06-25 14:59
Hey there, I've fixed the first bug you reported, haven't been able to reproduce the second. 

Could you upgrade and let me know whether the second one still happens?

**Comment by kwellman** [comment] 2010-06-25 20:44
I'm actually having problems running the new version. I get this error when running "visage start":

./visage:13:in `start': wrong number of arguments (1 for 0) (ArgumentError)
        from ./visage:13

**Comment by auxesis** [comment] 2010-06-25 21:55
Bummer. 

A few questions: 
- What version of the visage-app gem to do you have installed?
- What version of RubyGems do you have installed?
- What distro + version of Linux are you using?
- What's the output of `gem which visage-app`?
- Do you have the visage gem installed as well (not just the visage-app one)?

**Comment by kwellman** [comment] 2010-06-25 22:22
Thank you for taking the time to look at this.

Visage-app gem version 0.1.8 is installed.

RubyGems version 1.3.5 is installed

My distro is Ubuntu 9.10 Karmic 64 bit

gem which visage-app output:
(checking gem visage-app-0.1.8 for visage-app)
/home/kwellman/.gem/ruby/1.8/gems/visage-app-0.1.8/lib/visage-app.rb

The visage gem is not installed.

**Comment by auxesis** [comment] 2010-06-26 01:59
Thanks for passing on these details, and your patience. :-)

I'll try to recreate your environment and get back to you by tomorrow (crazy busy day today!).

**Comment by auxesis** [comment] 2010-06-27 22:22
Hey again, I managed to reproduce the bug, and will be working on a fix today.

**Comment by auxesis** [comment] 2010-06-27 22:25
Oh wait, that wasn't clear - I fixed the "visage start" problem (upgrade to 0.2.1 for the fix), and can reproduce the rendering bug.

**Comment by auxesis** [comment] 2010-10-15 13:57
I've found a dataset where I can reliably reproduce the all-zero rendering bug, but it's nestled deep in Raphaël. 

I'm quite jazzed about [Highcharts](http://www.highcharts.com/), and I'm debating whether to fix this bug or leave it be and just switch to Highcharts. 

Mind if I leave this unfixed for a little longer?

**Comment by kwellman** [comment] 2010-10-15 19:04
This bug doesn't really affect my usage of Visage, so, yeah, your time may be better spent on other features. It's a minor cosmetic issue to me.

**Comment by auxesis** [comment] 2010-10-16 10:51
No worries - thanks for the feedback! 

Closing for now, just open it up again if it's killing you.

**Closed as completed by auxesis** 2010-10-16 10:51 UTC
Labels: Bug
