### ISSUE TITLE
Visage won't start

### ISSUE THREAD

**Issue by nicinabox** [auxesis/visage#68] opened 2011-05-07 18:36 UTC
Seems to exit immediately
    nic@spinoza:~$ visage-app start
     _    ___
    | |  / (_)________ _____ ____
    | | / / / **_/ __ `/ __`/ _ \
    | |/ / (**  ) /_/ / /_/ /  **/
    |_**/_/____/__,_/__, /___/
                     /____/

```
will be running at http://spinoza.nicinabox.com:9292/

nic@spinoza:~$ 
```

Running strace gives this at the end:
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/collectd-0.0.15/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/collectd-0.0.15/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/collectd-0.0.15/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/errand-0.7.2/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/errand-0.7.2/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/errand-0.7.2/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.0.25/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.0.25/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/haml-3.0.25/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/hoe-2.9.4/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/hoe-2.9.4/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/hoe-2.9.4/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rake-0.8.7/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/tilt-1.2.2/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/tilt-1.2.2/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/tilt-1.2.2/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-0.2.5/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-0.2.5/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-0.2.5/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/yajl-ruby-0.8.2/lib/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/yajl-ruby-0.8.2/lib/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/yajl-ruby-0.8.2/lib/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/yajl-ruby-0.8.2/ext/RRD", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/yajl-ruby-0.8.2/ext/RRD.rb", 0xbfef9b94) = -1 ENOENT (No such file or directory)
    lstat64("/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/yajl-ruby-0.8.2/ext/RRD.so", 0xbfef9b94) = -1 ENOENT (No such file or directory)

Thoughts?

**Comment by Akhavi** [comment] 2011-05-08 10:24
Try:

gem install librrd

**Comment by auxesis** [comment] 2011-05-09 03:12
My initial reaction is a +1 to `gem install librrd` when using RVM. 

I don't know the details of how RVM and the system-wide Ruby libraries work. I'm vaguely familiar with RVM, but I have some specific questions you may be able to answer: 
- Can RVM use system-installed Ruby libraries?
- If not, can RVM use system-installed C headers when compiling C extensions?

I assume the answer to the first question is no, given it'd nastily break the ABI in all sorts of places.

I guess the second is possible, which is where `gem install librrd` would help you, assuming you have the necessary RRDtool headers installed on your system. 

Worst case, [rrd-ffi](https://github.com/morellon/rrd-ffi) may help if you don't mind a bit of hacking. :-)

Documentation should be updated to help RVM users.

**Comment by nicinabox** [comment] 2011-05-09 14:30
@Akhavi
Seems that librrd has to be installed on the system level

```
nic@spinoza:~$ gem install librrd
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /home/nic/.rvm/gems/ruby-1.9.2-p180/gems/librrd-1.0.0/CHANGES.md
nic@spinoza:~$ 
```

@auxesis
I'm not sure about either of those questions. My initial thought is that rvm needs to be setup for system-wide use rather than just gemset use. I can't install gems on the system level like that. :(

**Comment by nicinabox** [comment] 2011-05-09 14:31
^^ The comment & Close button is bigger :P

**Comment by Akhavi** [comment] 2011-05-09 14:50
Sudo first?

sudo gem install librrd

**Comment by nicinabox** [comment] 2011-05-09 14:58
That doesn't seem to quite work right either http://pastie.org/1881444. It's trying to use the system ruby then, which is 1.8. Seems like there might be some extra steps required for rvm?

**Comment by Akhavi** [comment] 2011-05-09 15:08
It did install librrd

Which ruby executable are you using?

/usr/bin/ruby ?

**Comment by nicinabox** [comment] 2011-05-09 15:11
Nope

```
nic@spinoza:~$ which ruby
/home/nic/.rvm/rubies/ruby-1.9.2-p180/bin/ruby
```

**Comment by Akhavi** [comment] 2011-05-09 15:36
Ok so try:

Sudo /home/nic/.rvm/rubies/ruby-1.9.2-p180/bin/gem install librrd

**Comment by nicinabox** [comment] 2011-05-09 15:45
Exact same output as http://pastie.org/1881444
What the heck :/

**Comment by auxesis** [comment] 2011-05-09 23:04
To clarify, does running `sudo /home/nic/.rvm/rubies/ruby-1.9.2-p180/bin/gem install librrd` result in
- the gem being installed?
- the aforementioned "Permission denied" error?

If it's installed, what does the output of `sudo /home/nic/.rvm/rubies/ruby-1.9.2-p180/bin/gem contents librrd` look like?

**Comment by nicinabox** [comment] 2011-05-10 16:03
`sudo /home/nic/.rvm/rubies/ruby-1.9.2-p180/bin/gem install librrd` gives http://pastie.org/1885508. The gem appears to install, no permission denied error.

`sudo /home/nic/.rvm/rubies/ruby-1.9.2-p180/bin/gem contents librrd` gives this output: http://pastie.org/1885517

...and as I went to test it magically worked :)

```
nic@spinoza:~$ visage-app start
 _    ___
| |  / (_)________ _____ ____
| | / / / ___/ __ `/ __ `/ _ \
| |/ / (__  ) /_/ / /_/ /  __/
|___/_/____/\__,_/\__, /\___/
                 /____/

will be running at http://spinoza.nicinabox.com:9292/

Looking for RRDs in /var/lib/collectd/rrd

[2011-05-10 11:00:13] INFO  WEBrick 1.3.1
[2011-05-10 11:00:13] INFO  ruby 1.9.2 (2011-02-18) [i686-linux]
[2011-05-10 11:00:13] WARN  TCPServer Error: Address already in use - bind(2)
[2011-05-10 11:00:13] INFO  WEBrick::HTTPServer#start: pid=4239 port=9292
```

**Comment by nicinabox** [comment] 2011-05-10 16:07
I do receive an error in the shell when trying to view a profile that's setup

```
[10/May/2011:11:05:05 CDT] "GET /data/spinoza.nicinabox.com/cpu-1/cpu-idle,cpu-interrupt,cpu-nice,cpu-softirq,cpu-steal,cpu-system,cpu-user,cpu-wait?callback=Request.JSONP.request_map.request_1 HTTP/1.1" 500 165696
http://spinoza.nicinabox.com:9292/profiles/spinoza -> /data/spinoza.nicinabox.com/cpu-1/cpu-idle,cpu-interrupt,cpu-nice,cpu-softirq,cpu-steal,cpu-system,cpu-user,cpu-wait?callback=Request.JSONP.request_map.request_1
TypeError: wrong argument type Array (expected Struct)
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/errand-0.7.2/lib/errand.rb:52:in `fetch'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/errand-0.7.2/lib/errand.rb:52:in `fetch'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/visage-app/collectd/json.rb:56:in `block in encode'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/visage-app/collectd/json.rb:55:in `each'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/visage-app/collectd/json.rb:55:in `encode'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/visage-app/collectd/json.rb:46:in `json'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/visage-app-0.9.4/lib/visage-app.rb:94:in `block in <class:JSON>'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:1064:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:1064:in `block in compile!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:649:in `instance_eval'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:649:in `route_eval'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:633:in `block (2 levels) in route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:681:in `block in process_route'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:678:in `catch'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:678:in `process_route'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:632:in `block in route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:631:in `each'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:631:in `route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:766:in `dispatch!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:559:in `block in call!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `instance_eval'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `block in invoke'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `catch'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `invoke'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:559:in `call!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:544:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/showexceptions.rb:24:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:614:in `forward'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:695:in `route_missing'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:644:in `route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:640:in `route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:640:in `route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:766:in `dispatch!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:559:in `block in call!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `instance_eval'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `block in invoke'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `catch'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `invoke'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:559:in `call!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:544:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/showexceptions.rb:24:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:614:in `forward'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:695:in `route_missing'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:644:in `route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:640:in `route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:640:in `route!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:766:in `dispatch!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:559:in `block in call!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `instance_eval'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `block in invoke'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `catch'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:731:in `invoke'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:559:in `call!'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/sinatra-1.1.4/lib/sinatra/base.rb:544:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/showexceptions.rb:24:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/content_length.rb:13:in `call'
/home/nic/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.2.2/lib/rack/handler/webrick.rb:52:in `service'
/home/nic/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:111:in `service'
/home/nic/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/httpserver.rb:70:in `run'
/home/nic/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/webrick/server.rb:183:in `block in start_thread'
```

**Comment by auxesis** [comment] 2011-05-11 11:22
That is a deep dark bug somewhere in the depths of RRD. 

@bernd, have any idea what might be causing this?

**Comment by auxesis** [comment] 2011-05-11 15:06
Ok, prototyped a quick implementation of Visage + Errand + rrd-ffi, which may get you where you need to be. To test it out:

``` bash
git clone --branch rrd-ffi git://github.com/auxesis/visage.git
cd visage
bundle install
RRD_LIB=$(ls -1 --color=none /usr/lib/librrd.so* |head -n 1) shotgun lib/visage-app/config.ru -o 0.0.0.0 -p 9292
```

This should work just fine with RVM (and likely JRuby), and you won't need the rrdtool-dev packages installed either. 

Let me know how it works for you!

**Comment by bernd** [comment] 2011-05-16 09:53
auxesis [Wed, May 11, 2011 at 04:23:00AM -0700] wrote:

> That is a deep dark bug somewhere in the depths of RRD. 
> 
> @bernd, have any idea what might be causing this?
> 
> Nope, sorry. Haven't had any problems like that yet.

**Comment by auxesis** [comment] 2011-05-18 08:21
@bernd no worries, thought as much. 

@nicinabox: curious to hear how the rrd-ffi version of Visage went for you?

**Comment by nicinabox** [comment] 2011-05-18 14:47
Ah, I got very sick on the day you posted that and forgot to try it out.

Using Ubuntu 10.04:
As far as I can tell now (on the same machine) there's no difference. It starts up but the `TypeError: wrong argument type Array (expected Struct)` error as before. 

Using OS X:
    `LoadError: Could not open library 'rrd': dlopen(rrd, 5): image not found. Could not open library 'librrd.dylib': dlopen(librrd.dylib, 5): image not found`

**Comment by bernd** [comment] 2011-06-24 18:07
I was finally able to reproduce this. (by accident) I'm getting the very same error when I try to load and run
a `RRD.so` file that has been built for ruby 1.8.7 with ruby 1.9.2.

```
<TypeError: wrong argument type Array (expected Struct)>
```

When I rebuild the `RRD.so` file with ruby 1.9.2 it works fine.

@nicinabox Your ruby/rvm setup might have been doing strange things. Not sure if you solved it already.

**Comment by nicinabox** [comment] 2011-06-24 21:22
Ah interesting. How did you rebuild the file?

**Comment by bernd** [comment] 2011-06-25 09:29
You can rebuild the gem with `gem pristine -V librrd`.

The `-V` option will show you the build output.

**Comment by auxesis** [comment] 2012-04-09 20:14
Looks like this issue was solved. 

Closing.

**Closed as completed by auxesis** 2012-04-09 20:14 UTC
Labels: Bug
